import Link from 'next/link'
import { ArrowUpRight, CheckCircle2, Play, Star } from 'lucide-react'
import type { Agent } from '@/lib/kymera'

export function Score({ score }: { score: number }) { return <div className="flex items-center gap-2"><div className="relative size-10"><svg className="size-10 -rotate-90" viewBox="0 0 36 36"><circle cx="18" cy="18" r="15" fill="none" stroke="#f0ede8" strokeWidth="3"/><circle cx="18" cy="18" r="15" fill="none" stroke="#e95d25" strokeWidth="3" strokeDasharray={`${score} 100`} pathLength="100" strokeLinecap="round"/></svg><span className="absolute inset-0 flex items-center justify-center text-[11px] font-semibold">{score}</span></div><span className="text-xs text-[#858078]">KY score</span></div> }

export function AgentCard({ agent, selected, onSelect }: { agent: Agent; selected?: boolean; onSelect?: (id: string) => void }) { return <article className={`group flex flex-col rounded-2xl border bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#d7d2cb] hover:shadow-[0_12px_30px_rgba(45,35,25,0.06)] ${selected ? 'border-[#e95d25] ring-2 ring-[#ffe1d3]' : 'border-[#e9e7e2]'}`}><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-xl text-sm font-bold text-white" style={{ background: agent.accent }}>{agent.symbol}</div><div><div className="flex items-center gap-1.5"><h3 className="font-semibold tracking-tight">{agent.name}</h3>{agent.verified && <CheckCircle2 size={14} className="text-[#e95d25]"/>}</div><p className="text-xs text-[#858078]">{agent.creator}</p></div></div><Score score={agent.score}/></div><p className="mt-5 min-h-12 text-sm leading-6 text-[#6f6c66]">{agent.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{agent.tags.map((tag) => <span key={tag} className="rounded-md bg-[#f6f5f2] px-2 py-1 text-[11px] text-[#77736c]">{tag}</span>)}</div><div className="mt-5 grid grid-cols-3 divide-x divide-[#eeeae5] border-y border-[#eeeae5] py-3"><Metric label="Runs" value={agent.runs}/><Metric label="Success" value={agent.success}/><Metric label="30d" value={agent.change} positive={agent.change.startsWith('+')}/></div><div className="mt-4 flex items-center justify-between"><span className={`flex items-center gap-1.5 text-xs ${agent.status === 'Live' ? 'text-[#138a61]' : 'text-[#a07627]'}`}><span className="size-1.5 rounded-full bg-current"/>{agent.status}</span><div className="flex gap-2">{onSelect && <button onClick={() => onSelect(agent.id)} className="rounded-lg border border-[#e2ded8] px-3 py-2 text-xs font-medium hover:bg-[#fafaf9]">{selected ? 'Selected' : 'Compare'}</button>}<Link href={`/agents/${agent.id}`} className="flex items-center gap-1 rounded-lg bg-[#171717] px-3 py-2 text-xs font-medium text-white hover:bg-[#333]">View <ArrowUpRight size={13}/></Link></div></div></article> }
function Metric({ label, value, positive }: { label: string; value: string; positive?: boolean }) { return <div className="px-2 first:pl-0 last:pr-0"><div className="text-[10px] uppercase tracking-wider text-[#aaa49c]">{label}</div><div className={`mt-1 text-sm font-semibold ${positive ? 'text-[#138a61]' : ''}`}>{value}</div></div> }

export function EmptyState({ query }: { query: string }) { return <div className="rounded-2xl border border-dashed border-[#d9d4cd] bg-white px-6 py-16 text-center"><Star className="mx-auto text-[#e95d25]" size={22}/><h3 className="mt-3 font-semibold">No agents found</h3><p className="mt-1 text-sm text-[#77736c]">Try a different search or clear your filters.</p></div> }
