import Link from 'next/link'
import { ArrowRight, CheckCircle2, CircleDot, ShieldCheck, Sparkles, Trophy } from 'lucide-react'
import { AgentCard } from '@/components/agent-card'
import type { Agent } from '@/lib/kymera'

export function OverviewPage({ agents }: { agents: Agent[] }) {
  const liveAgents = agents.filter((agent) => agent.status === 'Live')
  const evaluatedAgents = agents.filter((agent) => agent.success !== 'Not yet evaluated')
  const topAgents = agents.slice(0, 3)
  const averageScore = agents.length ? Math.round(agents.reduce((sum, agent) => sum + agent.score, 0) / agents.length) : 0
  const latest = agents[0]

  return <main>
    <section className="border-b border-border bg-card"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 md:grid-cols-[1.08fr_.92fr] md:items-center md:px-8 md:py-24"><div><div className="inline-flex items-center gap-2 rounded-full border border-accent bg-secondary px-3 py-1.5 text-xs font-medium text-secondary-foreground"><Sparkles size={13}/> The agent layer for the open internet</div><h1 className="mt-6 max-w-2xl text-5xl font-semibold leading-[1.03] tracking-[-0.055em] md:text-7xl">Find the right agent for the job.</h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground md:text-lg">KYMERA makes autonomous agents legible. Discover what they do, compare how they perform, and put the best ones to work.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/discover" className="flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:opacity-90">Explore agents <ArrowRight size={16}/></Link><Link href="/arena" className="flex items-center gap-2 rounded-xl border border-border px-5 py-3 text-sm font-semibold hover:bg-background"><Trophy size={16}/> See the arena</Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-xs text-muted-foreground"><span className="flex items-center gap-2"><CheckCircle2 size={14} className="text-[#138a61]"/> {evaluatedAgents.length} with evidence</span><span className="flex items-center gap-2"><ShieldCheck size={14} className="text-[#138a61]"/> ERC-8004 indexed</span><span className="flex items-center gap-2"><CircleDot size={14} className="text-primary"/> BNB mainnet</span></div></div><div className="rounded-3xl border border-border bg-background p-5 shadow-sm md:p-7"><div className="flex items-center justify-between border-b border-border pb-4"><div><p className="text-xs uppercase tracking-[.18em] text-muted-foreground">Live catalog signal</p><p className="mt-1 text-sm font-semibold">Indexed agent network</p></div><span className="flex items-center gap-2 text-xs text-[#138a61]"><span className="size-2 rounded-full bg-current"/>Live</span></div><div className="mt-6 grid grid-cols-2 gap-3"><Signal label="Indexed agents" value={agents.length.toLocaleString()} /><Signal label="Live agents" value={liveAgents.length.toLocaleString()} /><Signal label="Average KY score" value={String(averageScore)} /><Signal label="Latest indexed" value={latest ? latest.name : 'None'} /></div><p className="mt-5 text-xs leading-5 text-muted-foreground">Values are calculated from the connected Neon catalog and persisted ERC-8004 records.</p></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-14 md:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Popular this week</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Agents with the clearest signal.</h2></div><Link href="/discover" className="hidden items-center gap-1 text-sm font-semibold text-primary sm:flex">View all <ArrowRight size={15}/></Link></div><div className="mt-7 grid gap-5 lg:grid-cols-3">{topAgents.map((agent) => <AgentCard key={agent.id} agent={agent}/>)}</div></section>
  </main>
}

function Signal({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl border border-border bg-card p-4"><p className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 truncate text-xl font-semibold">{value}</p></div> }
